import 'package:flutter/material.dart';
//import 'package:http/http.dart' as http;
//import 'package:url_launcher/url_launcher.dart';
import 'dart:async';
import '../user/user.dart' as user;
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';


//var client = 'clients/${user.client}';
//var homework = 'homework/${user.client}';
//final DocumentReference docRefC = Firestore.instance.document(client);
//final DocumentReference docRefH = Firestore.instance.document(homework);
final dbC = Firestore.instance.collection('clients');


class Admin extends StatefulWidget {
  @override
  _AdminState createState() => _AdminState();
}

class _AdminState extends State<Admin> {
//  final client ="";
//  final address ="";
//  final city = " ";
//  final first ="";
//  final last ="";
//final startdate =1533524538;

  final _client = new TextEditingController();
  final _address = new TextEditingController();
  final _city= new TextEditingController();
  final _startdate= new TextEditingController();


  void addClient() {

    var newClient = {
      'client': _client.value.text,
      //todo fix - this works, but database id is bs (autogenerated, set id to client name?)
//      'address': _address.value.toString(),
//      'city': _city.value.toString(),
//      'startdate': _startdate.value.,
    };
dbC.add(newClient)
    .catchError(() => debugPrint("not added"));
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        new ListView (

          children: <Widget>[
            new Column(

            children: <Widget>[
          new Padding(padding: EdgeInsets.symmetric(vertical:22.2, horizontal: 22.2)),
          new TextFormField(

            controller: _client,
            decoration: new InputDecoration(hintText: "Client"),
          ),
          new Padding(padding: EdgeInsets.symmetric(vertical:22.2, horizontal: 22.2)),
          new TextFormField(

            controller: _address,
            decoration: new InputDecoration(hintText: "Address"),
          ),

          new Padding(padding: EdgeInsets.all(15.0)),
          new TextFormField(
            controller: _city,
            decoration: new InputDecoration(hintText: "City"),
          ),
          new Padding(padding: EdgeInsets.all(15.0)),
          new TextFormField(
            controller: _startdate,
            keyboardType: TextInputType.datetime,

           //todo add datepicker functionality - https://www.youtube.com/watch?v=PGsL5-hiz58

            decoration: new InputDecoration(hintText: "Start Date"),
          ),
          new Padding(padding: EdgeInsets.fromLTRB(0.0, 25.0, 0.0, 15.0)),
          new FloatingActionButton(
            onPressed: addClient,

            tooltip: 'Add New Client',
            child: new Icon(Icons.lock),
          ),
        ],
    ),
        ],
    ),
    ],
    );
  }
}